version: '3.6'

services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        POETRY_GROUPS: test,code-quality,debug
    volumes:
      - ./:/home/app
    env_file:
      - .env
    ports:
      - 8080:8000
#   postgres:
#     command: ["postgres", "-c", "log_statement=all"]
#     environment:
#       - POSTGRES_USER=develop
#       - POSTGRES_PASSWORD=develop
#       - POSTGRES_DB=develop
#     image: postgres:13-alpine
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
